[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "brawlpy"
authors = [{name = "PyStarr", email = "pystarrorg@gmail.com"}]
dynamic = ["version", "description"]
